- hosts: all
  pre_tasks:
  - fail:
      msg: "The 'new_password_hash' variable is required."
    when: "new_password_hash is not defined"


  tasks:
  - user:
      name: "{{ target_user | default('pi') }}"
      update_password: always
      password: "{{ new_password_hash }}"
    become: yes
