all:
    hosts:
        master.rpi.map.apart:
        worker[1:3].rpi.map.apart:

kube-masters:
  hosts:
    master.rpi.map.apart:

kube-workers:
  hosts:
    worker[1:3].rpi.map.apart:

kube-nodes:
  children:
    kube-masters:
    kube-workers:
